# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/arunupscee/Desktop/xtortion/c37 compliance/c37 compliance.runs/synth_1/pmu_system_complete_256.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/arunupscee/Desktop/xtortion/c37 compliance/c37 compliance.cache/wt} [current_project]
set_property parent.project_path {/home/arunupscee/Desktop/xtortion/c37 compliance/c37 compliance.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu106:part0:2.6 [current_project]
set_property ip_output_repo {/home/arunupscee/Desktop/xtortion/c37 compliance/c37 compliance.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/Sample_fetcher.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/packet_validator.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/circular_buffer.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/cordic_calculator_256.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/cos.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/crc_ccitt_c37118.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/cycle_tracker.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/c37118_packet_formatter_6ch.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/dft.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/dft_sample_buffer.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/frequency_rocof_calculator_256.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/channel_extractor.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/pmu_6ch_processing_256.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/axi_packet_receiver_128bit.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/interpolation_engine.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/pmu_processing_top.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/pmu_processing_top_no_freq.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/position_calc.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/input_interface_complete.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/resampler_top.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/sample_counter.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/sine.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/tve_calculator.vhd}
  {/home/arunupscee/Desktop/xtortion/c37 compliance/vhdl_modules/pmu_system_complete_256.vhd}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top pmu_system_complete_256 -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef pmu_system_complete_256.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file pmu_system_complete_256_utilization_synth.rpt -pb pmu_system_complete_256_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
