#!/bin/bash
# ============================================================================
# Harmonic Waveform Test — Full PMU Pipeline with TEXTIO hex output
# ============================================================================
#
# Compiles all VHDL modules + harmonic test data package + testbench,
# elaborates tb_pmu_harmonics_test, and runs xsim simulation.
#
# The testbench drives 3000 harmonic-laden packets (10 cycles @ 50 Hz)
# through pmu_system_complete_256 and writes output C37.118 packets
# to sim_output/output_packets_hex.txt via TEXTIO.
#
# Usage:
#   ./run_harmonics_test.sh
#
# Author: Arun's PMU Project
# Date: February 2026
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_banner() {
    echo ""
    echo "======================================"
    echo "$1"
    echo "======================================"
    echo ""
}

print_step() {
    echo -e "${BLUE}[STEP $1]${NC} $2"
}

print_success() {
    echo -e "${GREEN}+${NC} $1"
}

print_error() {
    echo -e "${RED}!${NC} $1"
}

print_banner "Harmonic PMU Test (10 cycles, TEXTIO hex output) - Vivado xsim"

# Change to project root (c37 compliance/)
cd "$(dirname "$0")/.."
PROJECT_ROOT=$(pwd)

echo "Project directory: $PROJECT_ROOT"
echo ""

# ----------------------------------------------------------------------------
# Pre-Flight Checks
# ----------------------------------------------------------------------------

print_step "0" "Pre-flight checks"

if ! command -v xvhdl &> /dev/null; then
    print_error "xvhdl not found! Please source Vivado settings:"
    echo "  source /path/to/Vivado/2025.1/settings64.sh"
    exit 1
fi
print_success "Vivado xsim tools found"

# Check key files
MISSING=0
for f in \
    "vhdl_modules/pmu_system_complete_256.vhd" \
    "vhdl_modules/hann_window.vhd" \
    "vhdl_modules/freq_damping_filter.vhd" \
    "test_data_harmonics_constants.vhd" \
    "testbenches/tb_pmu_harmonics_test.vhd"; do
    if [ ! -f "$f" ]; then
        print_error "Missing: $f"
        MISSING=$((MISSING + 1))
    fi
done

if [ $MISSING -gt 0 ]; then
    print_error "$MISSING required file(s) missing!"
    echo "Have you run:  python3 scripts/generate_harmonic_test_data.py ?"
    exit 1
fi
print_success "All required files found"

mkdir -p sim_output logs
echo ""

# ----------------------------------------------------------------------------
# Step 1: Compile VHDL with xvhdl
# ----------------------------------------------------------------------------

print_step "1" "Compiling VHDL files with xvhdl"
echo ""

mkdir -p xsim.dir

# Compile order: leaf modules first, then composites, then testbench
# Same 26 design files as run_5cycle_test.sh, plus harmonics package + testbench
VHDL_FILES=(
    # ROMs
    "vhdl_modules/sine.vhd"
    "vhdl_modules/cos.vhd"
    # Resampler chain
    "vhdl_modules/circular_buffer.vhd"
    "vhdl_modules/sample_counter.vhd"
    "vhdl_modules/cycle_tracker.vhd"
    "vhdl_modules/position_calc.vhd"
    "vhdl_modules/Sample_fetcher.vhd"
    "vhdl_modules/interpolation_engine.vhd"
    "vhdl_modules/resampler_top.vhd"
    # DFT chain
    "vhdl_modules/dft_sample_buffer.vhd"
    "vhdl_modules/dft.vhd"
    # Post-DFT processing
    "vhdl_modules/cordic_calculator_256.vhd"
    "vhdl_modules/frequency_rocof_calculator_256.vhd"
    # Window and filter modules
    "vhdl_modules/hann_window.vhd"
    "vhdl_modules/freq_damping_filter.vhd"
    # Processing top modules
    "vhdl_modules/pmu_processing_top.vhd"
    "vhdl_modules/pmu_processing_top_no_freq.vhd"
    # System integration
    "vhdl_modules/axi_packet_receiver_128bit.vhd"
    "vhdl_modules/input_interface_complete.vhd"
    "vhdl_modules/channel_extractor.vhd"
    "vhdl_modules/packet_validator.vhd"
    "vhdl_modules/crc_ccitt_c37118.vhd"
    "vhdl_modules/c37118_packet_formatter_6ch.vhd"
    "vhdl_modules/tve_calculator.vhd"
    "vhdl_modules/pmu_6ch_processing_256.vhd"
    "vhdl_modules/pmu_system_complete_256.vhd"
    # Harmonic test data package (generated by Python)
    "test_data_harmonics_constants.vhd"
    # Testbench
    "testbenches/tb_pmu_harmonics_test.vhd"
)

COMPILE_ERRORS=0

: > logs/xvhdl_harmonics.log

for file in "${VHDL_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        print_error "File not found: $file"
        ((COMPILE_ERRORS++))
        continue
    fi

    echo -n "  Compiling $(basename "$file")... "

    if xvhdl --work work "$file" >> logs/xvhdl_harmonics.log 2>&1; then
        echo -e "${GREEN}OK${NC}"
    else
        echo -e "${RED}FAILED${NC}"
        ((COMPILE_ERRORS++))
        echo "    See logs/xvhdl_harmonics.log for details"
    fi
done

echo ""

if [ $COMPILE_ERRORS -gt 0 ]; then
    print_error "Compilation failed with $COMPILE_ERRORS error(s)"
    echo "Check logs/xvhdl_harmonics.log for details"
    tail -n 30 logs/xvhdl_harmonics.log
    exit 1
fi

print_success "All ${#VHDL_FILES[@]} files compiled successfully (0 errors)"
echo ""

# ----------------------------------------------------------------------------
# Step 2: Elaborate Design
# ----------------------------------------------------------------------------

print_step "2" "Elaborating design with xelab"
echo ""

xelab -debug typical work.tb_pmu_harmonics_test \
    -s tb_harmonics_sim >> logs/xelab_harmonics.log 2>&1

if [ $? -ne 0 ]; then
    print_error "Elaboration failed!"
    echo "Check logs/xelab_harmonics.log for details"
    tail -n 30 logs/xelab_harmonics.log
    exit 1
fi

print_success "Elaboration complete (0 errors)"
echo ""

# ----------------------------------------------------------------------------
# Step 3: Run Simulation
# ----------------------------------------------------------------------------

print_step "3" "Running simulation with xsim"
echo ""
echo "Running 10-cycle harmonic test..."
echo "Timeout: 400 ms simulation time (350 ms testbench + margin)"
echo ""

# Create simulation TCL script
cat > xsim_harmonics_run.tcl << 'EOF'
puts "Starting harmonic PMU simulation (10 cycles, 3000 packets)..."
puts ""
run 400 ms
puts ""
puts "Simulation complete!"
quit
EOF

xsim tb_harmonics_sim -tclbatch xsim_harmonics_run.tcl > logs/xsim_harmonics.log 2>&1

# xsim returns non-zero on assert failure (normal testbench termination)
print_success "Simulation finished"
echo ""

# ----------------------------------------------------------------------------
# Step 4: Analyze Results
# ----------------------------------------------------------------------------

print_step "4" "Analyzing results"
echo ""

LOG_FILE="logs/xsim_harmonics.log"
OUTPUT_FILE="sim_output/output_packets_hex.txt"

# Show key simulation markers
echo "Key simulation output:"
echo "------------------------------"
grep -E "\[OUTPUT\]|\[STIMULUS\]|\[SUMMARY\]|TIMEOUT|Total packets" "$LOG_FILE" | head -40
echo "------------------------------"
echo ""

# Check output file
if [ -f "$OUTPUT_FILE" ]; then
    LINE_COUNT=$(wc -l < "$OUTPUT_FILE")
    print_success "Output file exists: $OUTPUT_FILE ($LINE_COUNT lines)"

    # Check first line starts with AA01004C
    FIRST_WORD=$(head -1 "$OUTPUT_FILE" | cut -d' ' -f1)
    if [ "$FIRST_WORD" = "AA01004C" ]; then
        print_success "First packet starts with AA01004C (correct SYNC+FRAMESIZE)"
    else
        print_error "First packet starts with $FIRST_WORD (expected AA01004C)"
    fi
else
    print_error "Output file not found: $OUTPUT_FILE"
    echo "Check logs/xsim_harmonics.log for simulation errors"
fi

echo ""

# ----------------------------------------------------------------------------
# Final Summary
# ----------------------------------------------------------------------------

print_banner "Test Results Summary"

echo "  Input:  3000 harmonic packets (10 cycles @ 50 Hz)"

if [ -f "$OUTPUT_FILE" ]; then
    echo "  Output: $LINE_COUNT C37.118 packets in $OUTPUT_FILE"
else
    echo "  Output: NONE (simulation may have failed)"
fi

echo ""
echo "Generated Files:"
echo "  - logs/xvhdl_harmonics.log    (compilation)"
echo "  - logs/xelab_harmonics.log    (elaboration)"
echo "  - logs/xsim_harmonics.log     (simulation)"
echo "  - sim_output/output_packets_hex.txt  (output packets)"
echo ""

if [ -f "$OUTPUT_FILE" ] && [ "$LINE_COUNT" -ge 8 ]; then
    echo -e "${GREEN}======================================"
    echo "Simulation produced $LINE_COUNT output packets"
    echo "Run analysis with:"
    echo "  python3 scripts/analyze_harmonic_output.py $OUTPUT_FILE"
    echo -e "======================================${NC}"
    exit 0
else
    echo -e "${YELLOW}======================================"
    echo "Fewer than 8 output packets produced"
    echo "Check logs/xsim_harmonics.log for details"
    echo -e "======================================${NC}"
    exit 1
fi
